print("Good day,")
widgets = int(input("please enter the number of widgets: "))
gizmos = int(input("please enter the number of gizmos: "))
weight = (widgets*75)+(gizmos*112)
print(f'total weight is ${weight}')
